# Generated by Django 3.2.6 on 2021-08-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='사용자명')),
                ('permission_u', models.CharField(max_length=32, verbose_name='권한')),
                ('name_hs', models.CharField(max_length=32, verbose_name='이름')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('register_dttm', models.DateField(auto_now_add=True, verbose_name='가입날짜')),
            ],
            options={
                'verbose_name': '사용자 모임',
                'verbose_name_plural': '사용자 모임',
                'db_table': 'user_define_fuser_table',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_f_name', models.CharField(max_length=100)),
                ('file_a', models.FileField(upload_to='static/')),
                ('file_b', models.FileField(upload_to='static/')),
            ],
        ),
    ]
