# Generated by Django 3.2.6 on 2021-09-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erptest', '0002_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '업로드파일목록', 'verbose_name_plural': '업로드파일목록'},
        ),
        migrations.AlterModelTable(
            name='document',
            table='user_define_uploadfilestest_table',
        ),
    ]
